spring:
  application:
    name: jobSearch
  datasource:
    url: jdbc:h2:./db/jobsearch;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  mvc:
    static-path-pattern: /static/**
    log-request-details: false
  freemarker:
    expose-session-attributes: true

server:
  port:
   8089
logging:
  level:
    root: info
    org:
      hibernate:
        error
      springframework:
        security: debug
    sql: error
  pattern:
    file: '%d{yyyy-mm-dd hh:mm:ss} %-5level %logger{36} -msg%n'
  file:
    path: logs