spring:
  application:
  name:
   jobSearch
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
    sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
        data-locations: classpath:data.sql
server:
  port:
   8089
