spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: jobSearch
  datasource:
    url: jdbc:h2:./db/jobsearch;AUTO_SERVER=TRUE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  mvc:
#    static-path-pattern: /static/**
    log-request-details: false
  freemarker:
    expose-session-attributes: true

#================= Mail config
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${GOOGLE_APP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
#================= Mail config
  web:
    resources:
      static-locations: classpath:/static/, file:./data/images/

server:
  port:
   8089
logging:
  level:
    root: info
    org:
      hibernate:
        error
      springframework:
        security: error
    sql: error
  pattern:
    file: '%d{yyyy-mm-dd hh:mm:ss} %-5level %logger{36} -msg%n'
  file:
    path: logs


